### ISSUE TITLE
proxy keeps node process alive

### ISSUE THREAD

**Issue by zkat** [zkat/make-fetch-happen#29]
There's an issue, probably with the proxy libraries make-fetch-happen is using, where the node process is kept alive if you use m-f-h's proxying agent features. This is likely because some socket somewhere isn't closing, or the libraries are doing some keepalive thing without any timeouts.

To set up a local SOCKS proxy to test with:
1. enable SSH (in OSX, System Preferences -> Sharing -> Remote login)
2. ssh -vND 8888 "$USER@localhost"

To set up a local http(s) proxy to test with:
1. install a reverse proxy, such as Squid
2. Configure and run the proxy locally

You can use `PROXY={socks,http}://localhost:8888 node` to have make-fetch-happen pick it up. You should be able to hit any http or https service with m-f-h after that.

**Comment by zkat** [comment]
hint: @yyjdelete suggested trying something like https://github.com/JoshGlazebrook/socks/commit/c65706d6b95c1d002fcf61db828b3e11f7622b6e as a patch. I wonder if that's really what it would take. And why it would work.

There's an issue here that @TooTallNate's proxy projects seem to be... dead? So we may need to fork, or find something different. Perhaps it's a good idea to look into switching to https://npm.im/tunnel-agent? That's what `request` uses so it's definitely still maintained. I don't think it supports `socks` proxying though.

**Comment by pi0** [comment]
Test snippet:

```js
const fetch = require('make-fetch-happen')
process.env.PROXY='http://icanhazip.com' // Without this line works fine
fetch('http://icanhazip.com').then(console.log).catch(console.error)
```

**Comment by pi0** [comment]
Tried a simple attempt to catch object leaks.

```js
const fetch = require('make-fetch-happen')
const heapdump = require('heapdump')

const dump = () => new Promise((resolve,reject) => heapdump.writeSnapshot((err, filename) => {  
  if(err) reject(err);
  resolve();
  console.log('dump written to', filename)
}))

const test = () => fetch('http://icanhazip.com').then(console.log).catch(console.error)

test().then(dump).then(() => {
	process.env.PROXY = 'http://icanhazip.com'
	test().then(dump)
});
```

You can compare two heap dumps. Seems `HTTPProxyAgent` is keeping process open.

![image](https://cloud.githubusercontent.com/assets/5158436/26424265/dc842c2c-40e5-11e7-9eae-e6d93e222196.png)

**Comment by TooTallNate** [comment]
> There's an issue here that @TooTallNate's proxy projects seem to be... dead?

Come again? Is there a pull request I need to address?

**Comment by zkat** [comment]
@TooTallNate oh! Great! Sorry, I saw that it'd been a few years since a release and didn't wanna bother you. I might end up having a pull request for you then -- just gotta figure out why using the proxies is keeping the node process alive 👍

**Comment by TooTallNate** [comment]
Sounds great! Ya all my proxy modules have mostly been completed, hence the small amount of activity. But I'm here if you need help or find bugs.

**Comment by zkat** [comment]
@TooTallNate do you have any idea where to look for why this particular bug is happening? It's definitely only when going through one of these proxies.

**Comment by TooTallNate** [comment]
`process._getActiveHandles()` and/or `process._getActiveRequests()` _might_ shed some light, but in general I've had a hard time making heads or tails of the results in the past.

If you can put together a simplified test case I can take a look.

**Comment by zkat** [comment]
Will do! I'll push that onto the stack :)

**Comment by yyjdelete** [comment]
@zkat @TooTallNate 
JoshGlazebrook/socks@c65706d is for another issue that socks-proxy can't get response for http/ws. Tested with the example code of `node-socks-proxy-agent` and node 7.9

And found there is already an PR for http as TooTallNate/node-socks-proxy-agent#12.

**Comment by zkat** [comment]
I'm having a hard time coming up with a repro step isolated from npm itself :( I'll have to take a look at this much later, then, unless someone else picks it up. I've really no clue right now.

**Comment by zkat** [comment]
Heads-up: The npm-side repro case is going away as of the latest beta 'cause I worked around the dangling socket issue (by calling `process.exit()` directly when commands finish, whereas the CLI would usually let the process exit by itself). This is still an issue for `make-fetch-happen` itself, though.

**Comment by pi0** [comment]
@TooTallNate Thanx for your suggestion `_getActiveHandles` helped a lot. This problem should be resolved by calling `unref` on proxy sockets.

> Calling unref on a socket will allow the program to exit if this is the only active socket in the event system. If the socket is already unrefd calling unref again will have no effect.

**Comment by TooTallNate** [comment]
@zkat @pi0 Sorry for the radio silence on this one. It's still on my radar I promise.

I'm actually having trouble reproducing the issue locally, using a modified version of the example script in the README:

```js
const fetch = require('./').defaults({
  cacheManager: './my-cache' // path where cache will be written (and read)
})

async function main() {
  let res
  let body

  res = await fetch('https://registry.npmjs.org/make-fetch-happen')
  console.log(res.status) // 200!
  body = await res.json() // download the body as JSON
  console.log(`got ${body.name} from web`)

  res = await fetch('https://registry.npmjs.org/make-fetch-happen', {
    cache: 'no-cache' // forces a conditional request
  })
  console.log(res.status) // 304! cache validated!
  body = await res.json() // download the body as JSON
  console.log(`got ${body.name} from cache`)
}

main().catch(console.error)
```

When running with squid, works as expected:

```
$ rm -rf my-cache/ && PROXY=http://localhost:3128 node t
200
got make-fetch-happen from web
304
got make-fetch-happen from cache
```

Or with a SSH socks proxy setup to my iMac at home:

```
$ rm -rf my-cache/ && PROXY=socks://localhost:8888 node t
200
got make-fetch-happen from web
304
got make-fetch-happen from cache
```

In both cases the process exits as expected (this is with Node 8.0.0).

---

On a completely separate note, I notice that the [`agent.js`](https://github.com/zkat/make-fetch-happen/blob/latest/agent.js) file has a lot of similarities to the [`proxy-agent`](https://github.com/tootallnate/node-proxy-agent) module, which is meant to be the high-level summation of my other *-proxy-agent modules.

`superagent-proxy` uses it to just depend on a single "proxy" module instead of "n" modules.

I think it would be really cool if m-f-h used that and we could move any necessary logic from your agent.js to `proxy-agent`. Let me know what you think!

**Comment by TooTallNate** [comment]
@pi0 fwiw, this line in your repro sample is not correct:

```js
process.env.PROXY='http://icanhazip.com' // Without this line works fine
```

icanhazip.com is _not_ an HTTP proxy. It is the _endpoint_ we are trying to connect to in this example. The `PROXY` variable should be set up to a Squid or Socks (or equivalent) proxy server URL, like how @zkat describes in the OP.

**Comment by zkat** [comment]
@TooTallNate I was using `proxy-agent` before and it was quite nice but had to move away because `pac-proxy-agent` is *massive* deps-wise and it seemed like a ton of MB to pull in for a feature I don't have any immediate need to support.

As far as a repro: I, too, tried to find a minimal repro isolated even to m-f-h but failed to do so. I know the difference was between using a proxy and not, but I could only ever repro this on npm itself. It's really weird. It might have to do with number of requests, or size of requests, or something completely different that happens to be triggered by this. I've no idea.

**Comment by TooTallNate** [comment]
PAC being massive was because it was doing transpilation using `regenerator` for versions of Node.js that did not support Generators. `pac-resolver@2` [fixed this issue](https://github.com/TooTallNate/node-pac-resolver/commit/df860eb96ba8490b6a2d5da12cf09d8ae1621d84) by dropping support for those older versions. Hopefully `proxy-agent` would end up being more lightweight at this point.

But I'd also be interested in looking into making all the http proxy types be opt-in as `peerDependencies`, and then `proxy-agent` would pick them up implicitly. That way m-f-h (and/or the end-user) could decide which proxy types to support.

**Comment by zkat** [comment]
oh great! I didn't like having to do this logic on m-f-h's end anyway. I'll make an issue to upgrade back to proxy-agent, then.

**Comment by jjimenez** [comment]
sorry to revive an old topic and I apologize for any misunderstanding of how things work in advance.  

We recently hit this issue on our project due to being behind a proxy when doing our project install.  I've tried to chase the issue down and it seems like the agent-base fix referenced here
https://github.com/TooTallNate/node-agent-base/pull/18
which brings agent-base to 4.2.1 would fix the issue.  It seems if this version ended up in your package_lock that would help the npm repo to bring it in.  It seems like npm is trying to update pacote to take care of this issue in 6.8, which depends on make-fetch-happen and on down to agent-base, but, and again, my understanding is limited, the package-locks end up having 4.2.0 and not 4.2.1 of agent base, so it won't fix the issue.  

If you think it would help, I could try to do a pull request to bump the version of agent-base that is in package_lock?

**Comment by zkat** [comment]
@jjimenez https://github.com/npm/cli/commit/6b70c02eeadbbdc662451c271c7bea84d62b981d I've bumped it in `release-next`, so it should be included in the next npm release.

I have also published an npm canary, if you'd like to test to confirm this actually got fixed for you. You can try it using `npx npmc@6.8.0-canary.2 install` and see if you still get the proxy hangups!

**Comment by jjimenez** [comment]
Thanks @zkat I'll see about running a local test!
