### ISSUE TITLE
Feature request: use http-cache-semantics package to evaluate cache freshness

### ISSUE THREAD

**Issue by kornelski** [zkat/make-fetch-happen#5]
I've created a package that very thoroughly parses and analyses HTTP cache headers. It supports a lot of edge cases and fine details such as the `Age` header and clearing of hop-by-hop headers required for pulling cached responses.

This package has a pretty good cache handling, but I believe the http-cache-semantics has a more complete implementation. I'd be delighted if you leveraged it in make-fetch-happen `</shameless-plug>`.

https://github.com/pornel/http-cache-semantics

**Comment by zkat** [comment]
Thanks for the suggestion! It sure would be nice to not maintain my own standards implementation for this.

I should look through the package to get a sense of it (and how it would fit into the current code structure), but if you integrate it and it still passes the test suite and doesn't affect the cache manager hookup API, I think I might take this PR.

I can give you a more definitive answer later when I'm back at a computer and have time to look through it in more detail. Cheers!

**Comment by zkat** [comment]
Ok! I had the time to snoop through the codebase. I don't think it's quite ready _right now_ to be used by make-fetch-happen, but I think this is a really good factoring of the problem, and it would be fantastic to move the bulk of this logic to an external library. Either way, this is a _really good_ reference to hack in the ugly version into make-fetch-happen, since you've done the work of finding and documenting all these little cases. I'd much rather have it all external, though! If you're interested in patching in the temporary version, that would be really helpful, too.

Some comments on http-cache-semantics:

* This definitely fixes some things that are missing or incorrect with make-fetch-happens' current cache implementation, specially around the dark corners. I definitely think it's worth the trouble to integrate this.

* Any libraries used by `make-fetch-happen` have to be compatible with `node@>=4` (at the npm package level, not at the source level). This is a hard requirement: `make-fetch-happen` is going to be used as the http backend for npm itself, and we support all maintained versions of node.

* The format for response and request, specially their headers, isn't compliant with `Headers` objects in `Response` and `Request`. To integrate without much adapter work, it would need to comply with that particular interface (for example, `.get()`, be case-insensitive, etc)

* Range requests are something I'd like to get working at some point, specially in combination with restarts. Caching ranges themselves is probably less important because the point is to be able to retry live requests. Still, it would be nice to have the option.

* This does not seem to have any awareness of its own that PUT/DELETE/POST methods on a resource should invalidate head/get (and possibly other stuff). I'm not sure http-cache-semantics would be able to do this anyway, since I guess it needs more awareness of caches.

* It would be nice to have concrete coverage information about the library. This is a lot of persnickety detail. :\

**Comment by kornelski** [comment]
* I've added Node 4 support: https://travis-ci.org/pornel/http-cache-semantics
* Currently the library uses format expected by Node and express. `node-fetch`'s `Headers` has a node-specific `.raw()` method which also exposes this format. 
* The library is spec-compliant regarding range requests, but it takes the option of making them non-cacheable. A meaningful support would require cache storage to be able to store and merge multiple ranges per representation, and that'd make a complicated API.
* If you store one response/`CachePolicy` per URL, then it'll behave properly for `PUT`/`DELETE`/`POST`, etc., since these are supposed to evict cached `GET`s.
* It's got 99% test coverage.

**Comment by zkat** [comment]
Awesome! Thanks for answering these questions! Are you interested in trying your hand at integration, or would you rather I do that when I get around to it?

**Comment by kornelski** [comment]
I'm short on time currently.

**Comment by zkat** [comment]
ok!

**Comment by zkat** [comment]
@pornel do you mind actually tagging a new release with the node@4 support? :) I've got a patch over at #13 that uses your lib. It's hacky, but it works, and it means I can get to other stuff. lol

**Comment by kornelski** [comment]
Published as v3.7.3

**Comment by zkat** [comment]
@pornel done :) I rushed through and I really need to get to #18 before the code stops being spaghetti, but it passes tests so whatever 😂 

Thanks again!

**Comment by kornelski** [comment]
Great! Thanks
